config/routes.rb
Rails.application.routes.draw do
  devise_for :administrators
  devise_for :students
  devise_for :companies

  get 'inicio/vacante'

  resources :vacantes

  resources :paneladmin, only: [:index, :show, :destroy]

  authenticated :student do
    root 'inicio#vacante'
  end

  unauthenticated :student do
    devise_scope :student do
      root "inicio#home", as: :sinregistro_root
    end
  end

end

app/models/vacante.rb
class Vacante < ActiveRecord::Base
	belongs_to :company
end

app/controllers/vacantes_controller.rb
class VacantesController < ApplicationController
  before_action :set_vacante, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_company!, except: [:destroy]

  # GET /vacantes
  # GET /vacantes.json
  def index
    @vacantes = current_company.vacantes
  end

  # GET /vacantes/1
  # GET /vacantes/1.json
  def show

  end

  # GET /vacantes/new
  def new
    @vacante = Vacante.new
  end

  # GET /vacantes/1/edit
  def edit
  end

  # POST /vacantes
  # POST /vacantes.json
  def create
    @vacante = current_company.vacantes.new(vacante_params)

    respond_to do |format|
      if @vacante.save
        format.html { redirect_to vacantes_path, notice: 'La Vacante a sido eliminada' }
        format.json { render :show, status: :created, location: @vacante }
      else
        format.html { render :new }
        format.json { render json: @vacante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vacantes/1
  # PATCH/PUT /vacantes/1.json
  def update
    respond_to do |format|
      if @vacante.update(vacante_params)
        format.html { redirect_to @vacante, notice: 'Vacante was successfully updated.' }
        format.json { render :show, status: :ok, location: @vacante }
      else
        format.html { render :edit }
        format.json { render json: @vacante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vacantes/1
  # DELETE /vacantes/1.json
  def destroy
    @vacante.destroy
    respond_to do |format|
      format.html { redirect_to vacantes_url, notice: 'Vacante was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vacante
      @vacante = Vacante.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vacante_params
      params.require(:vacante).permit(:title, :address, :salary, :description, :requirements, :benefits, :schedule, :category)
    end
end

app/helpers/vacantes_helper.rb
module VacantesHelper
end

app/views/vacantes/_form.html.erb
<%= form_for(@vacante) do |f| %>
  <% if @vacante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vacante.errors.count, "error") %> prohibited this vacante from being saved:</h2>

      <ul>
      <% @vacante.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title,'Título' %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :address,'Dirección' %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :salary,'Sueldo Ofrecido' %><br>
    <%= f.text_field :salary %>
  </div>
  <div class="field">
    <%= f.label :description,'Descripción' %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :requirements,'Requisitos' %><br>
    <%= f.text_area :requirements %>
  </div>
  <div class="field">
    <%= f.label :benefits,'Beneficios' %><br>
    <%= f.text_area :benefits %>
  </div>
  <div class="field">
    <%= f.label :schedule,'Horario' %><br>
    <%= f.text_field :schedule %>
  </div>
  <div class="field">
    <%= f.radio_button :category, 'Web' %> 
    <%= f.label :category, 'Web', :value => 'Web' %>
    <%= f.radio_button :category, 'Ventas' %>
    <%= f.label :category, 'Ventas', :value => 'Ventas' %>
  </div>
  
  <div class="actions flex-center">
    <%= f.submit "Crear Vacante", class: "waves-effect waves-light btn"%>
  </div>
<% end %>

app/views/vacantes/edit.html.erb
<h1>Editing Vacante</h1>

<%= render 'form' %>

<%= link_to 'Show', @vacante %> |
<%= link_to 'Back', vacantes_path %>

app/views/vacantes/index.html.erb
<div class="wrapper">
  <p id="notice"><%= notice %></p>

  <h4 class="center">Mis Vacantes</h4>

  <table>
    <thead>
      <tr>
        <th>Titulo</th>
        <th>Salario</th>
        <th>Descripción</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody class="tabla-fea2">
      <% @vacantes.each do |vacante| %>
        <tr>
          <td><%= vacante.title %></td>
          <td><%= vacante.salary %></td>
          <td><%= vacante.description %></td>
          <td><%= link_to 'Ver', vacante %></td>
          <td><%= link_to 'Editar', edit_vacante_path(vacante) %></td>
          <td><%= link_to 'Eliminar', vacante, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/vacantes/new.html.erb
<div class="wrapper">
	<h4>Crear Vacante</h4>

	<%= render 'form' %>

	<%= link_to 'Regresar', vacantes_path %>
	<br><br>
</div>

app/views/vacantes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @vacante.title %>
</p>

<p>
  <strong>Address:</strong>
  <%= @vacante.address %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @vacante.salary %>
</p>

<p>
  <strong>Description:</strong>
  <%= @vacante.description %>
</p>

<p>
  <strong>Requirements:</strong>
  <%= @vacante.requirements %>
</p>

<p>
  <strong>Benefits:</strong>
  <%= @vacante.benefits %>
</p>

<p>
  <strong>Schedule:</strong>
  <%= @vacante.schedule %>
</p>

<p>
  <strong>Category:</strong>
  <%= @vacante.category %>
</p>

<%= link_to 'Edit', edit_vacante_path(@vacante) %> |
<%= link_to 'Back', vacantes_path %>