config/routes.rb
Rails.application.routes.draw do
  devise_for :administrators
  devise_for :students
  devise_for :companies

  get 'inicio/vacante'

  resources :vacantes

  resources :paneladmin, only: [:index, :show, :destroy]

  authenticated :student do
    root 'inicio#vacante'
  end

  unauthenticated :student do
    devise_scope :student do
      root "inicio#home", as: :sinregistro_root
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <title>DIF</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div style="<%= "display:none;" if alert.nil? && notice.nil? %>">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>
	<nav class="teal white-text logo-space" role="navigation">
    <div class="nav-wrapper container">
      <%=link_to (image_tag "DoItFast.png", class: "logo"), root_path %>
      <ul class="right hide-on-med-and-down">
        
        
        <% if current_student %>
          <li>
            <%= link_to "Ver Perfil", edit_student_registration_path, {class: "white-text"} %>
          </li>
          <li>
            <%= link_to "Vacantes", inicio_vacante_path, {class: "white-text"} %>   
          </li>
          <% else %>
          <% if current_company %>
          <li><%= link_to 'Salir', destroy_company_session_path, method: :delete, :class =>"white-text" %></li>
          <% else %>
          <li><%= link_to ' Soy Empresa', new_company_session_path, {class: "white-text"} %></li>
          <% end %>
        <% end %>


        <% if current_company %>
          <li>
            <%= link_to "Ver Perfil", edit_company_registration_path, {class: "white-text"} %>
          </li>
          <li>
            <%= link_to "Ver Mis Vacantes", vacantes_path, {class: "white-text"} %>
          </li>
          <li>
            <%= link_to "Crear Vacante", new_vacante_path, {class: "white-text"} %>
          </li>
          <% else %>
          <% if current_student %>
          <li><%= link_to 'Salir', destroy_student_session_path, method: :delete, :class =>"white-text" %></li>
          <% else %>
          <li><%= link_to 'Soy Estudiante', new_student_session_path, {class: "white-text"} %></li>
          <% end %>
        <% end %>
      </ul>

      <ul id="nav-mobile" class="side-nav">
        <li><a href="#">Vacantes</a></li>
        <li><a href="#">Soy Empresa</a></li>
        <li><a href="#">Soy Estudiante</a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons white-text">Menú</i></a>
    </div>
  </nav>

  <%= yield %>

  <footer class="page-footer teal">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Sobre Nosotros</h5>
          <p class="grey-text text-lighten-4">Somos politecnicos, escomios de corazón. Apasionados por el desarrollo, amamos la Web, las buenas tendencias y las buenas canchas.</p>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Navegación</h5>
          <ul>
            <li><%= link_to "Vacantes", inicio_vacante_path, class: "white-text" %></li>
            <li><%= link_to "Login Estudiantes", new_student_session_path, class: "white-text" %></li>
            <li><%= link_to "Login Empresas", new_company_session_path, class: "white-text" %></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Síguenos</h5>
          <ul>
            <li><a class="white-text" href="https://www.facebook.com/tono.ricardo" target="_blank">Facebook</a></li>
            <li><a class="white-text" href="https://github.com/AntonioRF/" target="_blank">Git Hub</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Made by <a class="brown-text text-lighten-3" href="#">AntonioRF</a>
      </div>
    </div>
  </footer>

</body>
</html>